title: Blog
author: Bruno Alcebíades Vaz
email: bruno.asvaz03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog for the GitHub Learnig Lab's course about GitHub Pages

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
